### ISSUE TITLE
Unable to see Keep button

### ISSUE THREAD

**Issue by yimir0** [Garoe/ThunderKeepPlus#12]
I'm using TB 72.0b3 x64
I installed ThunderKeepPlus, but it doesn't ask for restart and I can't see the Keep button (even after a restart), not in the interface, nor in the customization window.
What am I doing wrong?

**Comment by Gara-Dorta** [comment]
I haven't tested thunderkeepplus on thunderbird 72 or 73 yet. I'll do some testing and get back to you. In any case, the addon uses the slightly more modern api that does not require a restart, so that is normal.

**Comment by yimir0** [comment]
Anyway, I switched to 68.4.2 version, and here all works fine

**Comment by archerindigo** [comment]
Hi, I also hit this issue on TB 68.5.0. The button sometime show-up but sometime not. Need to restart the addon to make it show-up again.

**Comment by Gara-Dorta** [comment]
Thanks for reporting the issue. I'm able to replicate the behaviour on TB 68.5, but I'm not sure what the underlying cause is. Moving the button position to a new location (right click -> customize) seems to mitigate the issue.

In any case, this should be solved once I update the code to use the new [WebExtensions API](https://developer.thunderbird.net/add-ons/about-add-ons). This is almost done, but some functionality needs to be implement by the Thunderbird developers in the new API for this addon to work. I've filed a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1618828), and once it is solved, a new release of ThunderKeepPlus should follow shortly after.

**Comment by frogstar51** [comment]
Hi, I've mistakenly closed the Keep tab and now I can't get it back.  I'm running Thunderbird 68.10.0 (32-bit)
I reinstalled Thunderbird with the latest from the web (Thunderbird 68.10.0 (32-bit)) I deleted the add-on and then reinstalled it but still can't get it to work.  Any help greatly appreciated.

**Comment by Gara-Dorta** [comment]
Hi, thanks for reporting this. The only known workaround is right clicking on the toolbar, selecting customize and moving back the icon to the toolbar. If this does not work, you can use the attached beta version, which has been rewritten to use the new API. However, this version does not allow closing the session or switching accounts. You'd have go to tools -> clear recent history and clear the cookies.
[ThunderKeepPlus-0.10.5beta-tb.zip](https://github.com/Garoe/ThunderKeepPlus/files/4891349/ThunderKeepPlus-0.10.5beta-tb.zip)

**Comment by frogstar51** [comment]
Thanks for replying.  I tried to customize but the icon wasn't there.  Turned my PC on this morning and looked again and now the icon is there, so moved it to the toolbar and everything works ok.  Thanks for taking the time to reply, it really is appreciated.
